//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ_Jewellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int prd_id { get; set; }
        public int prd_quantity { get; set; }
        public int prd_price { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
