//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ_Jewellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeweller
    {
        public string jeweller_id { get; set; }
        public string jeweller_name { get; set; }
        public string jeweller_password { get; set; }
    }
}
