//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ_Jewellers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JewelleryManagementSystemEntities : DbContext
    {
        public JewelleryManagementSystemEntities()
            : base("name=JewelleryManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRN> GRNs { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Jeweller> Jewellers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<Quotation_Request> Quotation_Request { get; set; }
        public virtual DbSet<Quotation_Response> Quotation_Response { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
