//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ_Jewellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int order_id { get; set; }
        public string payment_type { get; set; }
        public int netprice { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
