//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ_Jewellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation_Response
    {
        public int req_id { get; set; }
        public int vendor_id { get; set; }
        public int price_perunit { get; set; }
    
        public virtual Quotation_Request Quotation_Request { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
