//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZ_Jewellers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Quotation_Response = new HashSet<Quotation_Response>();
        }
    
        public int vendor_id { get; set; }
        public string vendor_name { get; set; }
        public string vendor_email { get; set; }
        public string vendor_password { get; set; }
        public string vendor_contact { get; set; }
        public string vendor_cnic { get; set; }
        public string vendor_address { get; set; }
        public int vendor_tax { get; set; }
        public string vendor_bank_name { get; set; }
        public string vendor_acc_title { get; set; }
        public string vendor_acc_no { get; set; }
        public string vendor_licenseNo { get; set; }
        public byte[] vendor_licenseImg { get; set; }
        public string vendor_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation_Response> Quotation_Response { get; set; }
    }
}
